version: '2'
services:
    illalimpa-app:
        image: illalimpa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://illalimpa-mysql:3306/illalimpa?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    illalimpa-mysql:
        extends:
            file: mysql.yml
            service: illalimpa-mysql
